### ISSUE TITLE
Experiment configuration

### ISSUE THREAD

**Issue by wj-son** [xuyu0010/ATCoN#7]
Thanks for your great work and fast response to issues.
It said that more specifications on benchmark details and network implementation are provided in the Appendix. 
As far as I know, the Appendix does not exist(or not opened yet?).
So, I want to implement your method with datasets except for UCF,HMDB and would you let me know the experiment configuration?

**Comment by xuyu0010** [comment]
Hi, thank you for your interest and questions. The appendix (or supplementary material) will be available after the ECCV conference next month.
I will add in a configuration file for the three datasets to the repo as soon as possible. I am unable to provide it now as the configurations are stored in a server where I currently do not have total free access due to policy issues.
