### ISSUE TITLE
Pretrained model check issue

### ISSUE THREAD

**Issue by wj-son** [xuyu0010/ATCoN#8]
Thanks for your great work and fast response to issues.
In the paper, it is written that all methods adopt the TRN as the backbone pre-trained on 'ImageNet'. As this might imply, it will be reasonable that the repored UCF-HMDB full 
 results and reimplemented results differ not so many. 
But, all the configuration is all the same with your file but the result is quite higher than table in the paper and the training procedure saturates so fast due to pre-trained weight. 
So, I wonder whether the backbone is pre-trained on 'ImageNet' or not (Kinetics400?) and think that you might mistake which is used to pre-training backbone.

**Comment by xuyu0010** [comment]
Sorry, I don't get your question. 

For the pretrained network, it is pretrained on ImageNet.

**Comment by xuyu0010** [comment]
Just to add on, from my own experience saturation speed could be affected by many issues, including but not limited to hardware settings, environment settings, weight settings, etc. This weight is adopted from a prior repository on TRN. For more information on TRN, you may visit the mmaction2/mmaction (which is no longer updating) repository.

**Comment by roysubhankar** [comment]
The authors could clarify what '_pre-training_' actually means? Does it mean:

1. first the Resnet50 backbone was pre-trained on Imagenet (using a supervised image classification objective), followed by training the Resnet50+TRN modules on some video dataset? Then this resulting checkpoint obtained at the end of this step was used by the ATCoN authors to train on the DA datasets (e.g. Daily DA) 
2. only the Resnet50 backbone was pre-trained on Imagenet and the authors of ATCoN initialized the TRN modules from scratch.

I presume that the first one (point number 1) is the most likely case because in the original mmaction2/mmaction readme page for TRN they have trained the TRN on video datasets, while starting from Imagenet pre-training. https://github.com/open-mmlab/mmaction2/blob/b7af9d329b610f32e29b6c1885330bb7d0afc942/configs/recognition/trn/README.md

For clarity the authors should point to the original checkpoint link of mmaction repo, from where they downloaded the tsn2d_rgb_r50.pth checkpoint.

Thank you.
